
import java.awt.event.ActionEvent;

public class calculadora extends javax.swing.JFrame {
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        tela = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        botao2 = new javax.swing.JButton();
        botao1 = new javax.swing.JButton();
        botaoC = new javax.swing.JButton();
        botao6 = new javax.swing.JButton();
        botao5 = new javax.swing.JButton();
        botao4 = new javax.swing.JButton();
        botao9 = new javax.swing.JButton();
        botao7 = new javax.swing.JButton();
        botao8 = new javax.swing.JButton();
        botao3 = new javax.swing.JButton();
        botaoSub = new javax.swing.JButton();
        botaoS = new javax.swing.JButton();
        Botaomult = new javax.swing.JButton();
        botao0 = new javax.swing.JButton();
        botaoDiv = new javax.swing.JButton();
        botaoResult = new javax.swing.JButton();
        botaoP = new javax.swing.JButton();

        jButton10.setText("jButton10");

        jLabel1.setText("jLabel1");

        jButton14.setText("=");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        tela.setBackground(new java.awt.Color(255, 255, 255));
        tela.setForeground(new java.awt.Color(0, 0, 0));
        tela.addComponentListener(new java.awt.event.ComponentAdapter() {
            
        });
        tela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telaActionPerformed(evt);
            }
        });

        botao2.setBackground(new java.awt.Color(255, 255, 255));
        botao2.setForeground(new java.awt.Color(0, 0, 0));
        botao2.setText("2");
        botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao2ActionPerformed(evt);
            }
        });

        botao1.setBackground(new java.awt.Color(255, 255, 255));
        botao1.setForeground(new java.awt.Color(0, 0, 0));
        botao1.setText("1");
        botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao1ActionPerformed(evt);
            }
        });

        botaoC.setBackground(new java.awt.Color(255, 255, 255));
        botaoC.setForeground(new java.awt.Color(0, 0, 0));
        botaoC.setText("C");
        botaoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCActionPerformed(evt);
            }
        });

        botao6.setBackground(new java.awt.Color(255, 255, 255));
        botao6.setForeground(new java.awt.Color(0, 0, 0));
        botao6.setText("6");
        botao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao6ActionPerformed(evt);
            }
        });

        botao5.setBackground(new java.awt.Color(255, 255, 255));
        botao5.setForeground(new java.awt.Color(0, 0, 0));
        botao5.setText("5");
        botao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao5ActionPerformed(evt);
            }
        });

        botao4.setBackground(new java.awt.Color(255, 255, 255));
        botao4.setForeground(new java.awt.Color(0, 0, 0));
        botao4.setText("4");
        botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao4ActionPerformed(evt);
            }
        });

        botao9.setBackground(new java.awt.Color(255, 255, 255));
        botao9.setForeground(new java.awt.Color(0, 0, 0));
        botao9.setText("9");
        botao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao9ActionPerformed(evt);
            }
        });

        botao7.setBackground(new java.awt.Color(255, 255, 255));
        botao7.setForeground(new java.awt.Color(0, 0, 0));
        botao7.setText("7");
        botao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao7ActionPerformed(evt);
            }
        });

        botao8.setBackground(new java.awt.Color(255, 255, 255));
        botao8.setForeground(new java.awt.Color(0, 0, 0));
        botao8.setText("8");
        botao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao8ActionPerformed(evt);
            }
        });

        botao3.setBackground(new java.awt.Color(255, 255, 255));
        botao3.setForeground(new java.awt.Color(0, 0, 0));
        botao3.setText("3");
        botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao3ActionPerformed(evt);
            }
        });

        botaoSub.setBackground(new java.awt.Color(204, 204, 204));
        botaoSub.setForeground(new java.awt.Color(0, 0, 0));
        botaoSub.setText("-");
        botaoSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSubActionPerformed(evt);
            }
        });

        botaoS.setBackground(new java.awt.Color(204, 204, 204));
        botaoS.setForeground(new java.awt.Color(0, 0, 0));
        botaoS.setText("+");
        botaoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSActionPerformed(evt);
            }
        });

        Botaomult.setBackground(new java.awt.Color(204, 204, 204));
        Botaomult.setForeground(new java.awt.Color(0, 0, 0));
        Botaomult.setText("X");
        Botaomult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaomultActionPerformed(evt);
            }
        });

        botao0.setBackground(new java.awt.Color(255, 255, 255));
        botao0.setForeground(new java.awt.Color(0, 0, 0));
        botao0.setText("0");
        botao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao0ActionPerformed(evt);
            }
        });

        botaoDiv.setBackground(new java.awt.Color(204, 204, 204));
        botaoDiv.setForeground(new java.awt.Color(0, 0, 0));
        botaoDiv.setText("/");
        botaoDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDivActionPerformed(evt);
            }
        });

        botaoResult.setBackground(new java.awt.Color(51, 51, 255));
        botaoResult.setForeground(new java.awt.Color(0, 0, 0));
        botaoResult.setText("=");
        botaoResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoResultActionPerformed(evt);
            }
        });

        botaoP.setBackground(new java.awt.Color(204, 204, 204));
        botaoP.setForeground(new java.awt.Color(0, 0, 0));
        botaoP.setText(".");
        botaoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botao0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoResult, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoSub, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Botaomult, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botao1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botao2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botao3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botao4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botao5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botao6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botao7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botao8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botao9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoP, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botao0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botaoDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoS, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(botaoSub, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Botaomult, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoResult, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Faz com que ao apertar em um botao seja adicionado o valor do botao ao display
    private void telaActionPerformed(java.awt.event.ActionEvent evt){
        
    }
    
    private void botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao2ActionPerformed
        tela.setText(tela.getText()+ "2");   
    }//GEN-LAST:event_botao2ActionPerformed

    private void botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ActionPerformed
        tela.setText(tela.getText()+ "1");
    }//GEN-LAST:event_botao1ActionPerformed

    private void botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao3ActionPerformed
        tela.setText(tela.getText()+ "3");
    }//GEN-LAST:event_botao3ActionPerformed

    private void botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao4ActionPerformed
        tela.setText(tela.getText()+ "4");
    }//GEN-LAST:event_botao4ActionPerformed

    private void botao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao5ActionPerformed
        tela.setText(tela.getText()+ "5");
    }//GEN-LAST:event_botao5ActionPerformed

    private void botao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao6ActionPerformed
        tela.setText(tela.getText()+ "6");
    }//GEN-LAST:event_botao6ActionPerformed

    private void botao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao7ActionPerformed
        tela.setText(tela.getText()+ "7");
    }//GEN-LAST:event_botao7ActionPerformed

    private void botao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao8ActionPerformed
        tela.setText(tela.getText()+ "8");
    }//GEN-LAST:event_botao8ActionPerformed

    private void botao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao9ActionPerformed
        tela.setText(tela.getText()+ "9");
    }//GEN-LAST:event_botao9ActionPerformed

    private void botao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao0ActionPerformed
        tela.setText(tela.getText()+ "0");
    }//GEN-LAST:event_botao0ActionPerformed

    private void botaoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPActionPerformed
        tela.setText(tela.getText()+ ".");
    }//GEN-LAST:event_botaoPActionPerformed

    private void botaoDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDivActionPerformed
        tela.setText(tela.getText()+ " / ");
    }//GEN-LAST:event_botaoDivActionPerformed

    private void BotaomultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaomultActionPerformed
        tela.setText(tela.getText()+ " x ");
    }//GEN-LAST:event_BotaomultActionPerformed

    private void botaoSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSubActionPerformed
         tela.setText(tela.getText()+ " - ");
    }//GEN-LAST:event_botaoSubActionPerformed

    private void botaoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSActionPerformed
         tela.setText(tela.getText()+ " + ");
    }//GEN-LAST:event_botaoSActionPerformed

    private void botaoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCActionPerformed
        tela.setText(" ");
    }//GEN-LAST:event_botaoCActionPerformed

    private void botaoResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoResultActionPerformed
       avaliarExpressao();
    }//GEN-LAST:event_botaoResultActionPerformed

    //Pega a expressão do display e armazena na variavel expressao
    public void avaliarExpressao() {
    String expressao = tela.getText();

    // Verifica se a expressão tem o operador de soma e faz a operação
    if (expressao.contains("+")) {
        String[] partes = expressao.split("\\+");
        if (partes.length == 2) {
            double num1 = Double.parseDouble(partes[0].trim());
            double num2 = Double.parseDouble(partes[1].trim());
            double resultado = num1 + num2;
            
             //Verifica se o valor é inteiro ou decimal e formata a saida
             if (resultado % 1 == 0) {
                tela.setText(String.valueOf((long) resultado)); // Se for inteiro, não arredonda
            } else {
                tela.setText(String.valueOf(resultado)); // Se for decimal, não arredonda
            }
             
        } else {
            tela.setText("Erro");
        }
    //Verifica se conter o operador negativo e faz a operação
    } else if (expressao.contains("-")) {
           String[] partes = expressao.split("-");
           if (partes.length == 2) {
               double num1 = Double.parseDouble(partes[0].trim());
               double num2 = Double.parseDouble(partes[1].trim());
               double resultado = num1 - num2;
               
               //Verifica se o valor é inteiro ou decimal e formata a saida
               if (resultado % 1 == 0) {
                    tela.setText(String.valueOf((long) resultado)); // Se for inteiro, não arredonda
                } else {
                    tela.setText(String.valueOf(resultado)); // Se for decimal, não arredonda
                }
               
           } else {
               tela.setText("Erro");
           }
    // Verifica se o operador é o de multiplicação e faz a operação
    } else if (expressao.contains("x")) {
           String[] partes = expressao.split("x");
           if (partes.length == 2) {
               double num1 = Double.parseDouble(partes[0].trim());
               double num2 = Double.parseDouble(partes[1].trim());
               double resultado = num1 * num2;
               
               //Verifica se o valor é inteiro ou decimal e formata a saida
               if (resultado % 1 == 0) {
                    tela.setText(String.valueOf((long) resultado)); // Se for inteiro, não arredonda
                } else {
                    tela.setText(String.valueOf(resultado)); // Se for decimal, não arredonda
                }
           } else {
               tela.setText("Erro");
           }
     //Verifica se o operador é de divisão e faz a operação   
    } else if (expressao.contains("/")) {
        String[] partes = expressao.split("/");
           if (partes.length == 2) {
               double num1 = Double.parseDouble(partes[0].trim());
               double num2 = Double.parseDouble(partes[1].trim());
               
               //Verifica se o divisor é 0, caso seja 0 ele volta a mensagem de erro
               if (num2 != 0) {
                    double resultado = num1 / num2;
                    
                    //Verifica se o valor é inteiro ou decimal e formata a saida
                    if (resultado % 1 == 0) {
                        tela.setText(String.valueOf((long) resultado)); // Se for inteiro, não arredonda
                    } else {
                        tela.setText(String.valueOf(resultado)); // Se for decimal, não arredonda
                    }
                } else {
                    tela.setText("Não é possivel dividir por zero");
                }
           } else {
               tela.setText("Erro");
           }
    } else {
        tela.setText("Expressão inválida");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botaomult;
    private javax.swing.JButton botao0;
    private javax.swing.JButton botao1;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JButton botao5;
    private javax.swing.JButton botao6;
    private javax.swing.JButton botao7;
    private javax.swing.JButton botao8;
    private javax.swing.JButton botao9;
    private javax.swing.JButton botaoC;
    private javax.swing.JButton botaoDiv;
    private javax.swing.JButton botaoP;
    private javax.swing.JButton botaoResult;
    private javax.swing.JButton botaoS;
    private javax.swing.JButton botaoSub;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tela;
    // End of variables declaration//GEN-END:variables
}
